### ISSUE TITLE
Make ChemicalListView wider

### ISSUE THREAD

**Issue by PythonFZ** [PythonFZ/ChemData#16]
Use more of the available screen width to display more information.

Note:
Always test on mobile as well!

**Comment by PythonFZ** [comment]
As shown [here](https://github.com/PythonFZ/ChemData/blob/9c61c616010460dc52952460353e79bbfef9be30/chemmanager/templates/chemmanager/base.html#L48#L54) we can add 
```css
@media (min-width: 1400px) {
    .container {
        max-width: 1600px;
    }
}
```

to change the max size of the container
